# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


trigger:
  branches:
    include:
    - master
    
stages:

- stage: Deploy_Dev
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy
    
    pool:
      vmImage: 'windows-latest'
      
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    
    environment: 'DEV'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'Pre Checking directories'
            inputs:
              script: echo $(System.DefaultWorkingDirectory)